/**
 * Resume Studio, inside the dashboard: your resumes, the template gallery, and
 * the editor — one view, no page navigation.
 */
import { AnimatePresence, motion } from 'framer-motion';
import { Loader2 } from 'lucide-react';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { flowLog } from '../../../lib/flowLog';
import TemplateCard from '../../resume/TemplateCard';
import ResumeCard from '../../resume/ResumeCard';
import ResumeEditorView from '../../resume/editor/ResumeEditorView';
import { useToastContext } from '../../ui/ToastProvider';
import { PRESETS, type PresetTag } from '../../../lib/resume/presets';
import type { ResumeDocument } from '../../../lib/resume/schema';
import { createFromPreset, deleteResume, duplicateResume, getResume, listResumes } from '../../../services/resumeService';

const TAGS: { id: PresetTag | 'all'; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'simple', label: 'Simple' },
  { id: 'modern', label: 'Modern' },
  { id: 'two-column', label: 'Two column' },
  { id: 'compact', label: 'Compact' },
  { id: 'classic', label: 'Classic' },
  { id: 'creative', label: 'Creative' },
];

const fade = {
  initial: { opacity: 0, y: 8 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -8 },
  transition: { duration: 0.22, ease: [0.22, 1, 0.36, 1] as const },
};

export default function ResumeStudioView({
  uid,
  openId,
  fresh,
}: {
  uid: string;
  openId?: string | null;
  /** The resume was just generated by the AI. */
  fresh?: boolean;
}) {
  const { showError, showSuccess } = useToastContext();
  const [resumes, setResumes] = useState<ResumeDocument[] | null>(null);
  const [editing, setEditing] = useState<ResumeDocument | null>(null);
  const [tag, setTag] = useState<PresetTag | 'all'>('all');
  const [creating, setCreating] = useState<string | null>(null);
  // True while a deep link is being resolved, so the list never flashes first.
  const [opening, setOpening] = useState(!!openId);

  const reload = useCallback(async () => {
    try {
      setResumes(await listResumes(uid));
    } catch {
      setResumes([]);
    }
  }, [uid]);

  useEffect(() => {
    void reload();
  }, [reload]);

  // Deep link: /dashboard?view=resumes&resume=<id> opens that resume directly.
  //
  // Each id is opened exactly once. This effect used to depend on the toast
  // functions, which changed on every render, so any toast re-ran it: it flipped
  // `opening` back on (unmounting the editor) and refetched over the user's
  // edits. It also must not cancel via cleanup: React's dev double-invoke would
  // cancel the only fetch and leave the spinner up forever.
  const showErrorRef = useRef(showError);
  showErrorRef.current = showError;
  const requestedRef = useRef<string | null>(null);
  useEffect(() => {
    if (!openId) {
      setOpening(false);
      return;
    }
    if (requestedRef.current === openId) return;
    requestedRef.current = openId;
    setOpening(true);
    flowLog(openId, 'studio:open-resume');
    getResume(uid, openId)
      .then((found) => {
        if (requestedRef.current !== openId) return; // a newer request replaced this one
        if (found) {
          flowLog(openId, 'studio:resume-loaded', { sections: found.sections.length, hasAi: Boolean(found.ai) });
          setEditing(found);
        } else {
          flowLog(openId, 'studio:resume-missing');
          showErrorRef.current('Could not open resume', 'It may have been deleted, or it could not be read.');
        }
      })
      .catch((error) => {
        flowLog(openId, 'studio:resume-error', { message: error instanceof Error ? error.message : String(error) });
        showErrorRef.current('Could not open resume', 'Please try again from your resume list.');
      })
      .finally(() => {
        if (requestedRef.current === openId) setOpening(false);
      });
  }, [openId, uid]);

  const templates = useMemo(() => (tag === 'all' ? PRESETS : PRESETS.filter((p) => p.tags.includes(tag))), [tag]);

  const start = useCallback(
    async (presetId: string) => {
      setCreating(presetId);
      try {
        setEditing(await createFromPreset(uid, presetId));
      } catch (e) {
        showError('Could not create resume', e instanceof Error ? e.message : 'Please try again.');
      } finally {
        setCreating(null);
      }
    },
    [showError, uid],
  );

  const duplicate = useCallback(
    async (source: ResumeDocument) => {
      try {
        const copy = await duplicateResume(uid, source);
        setResumes((prev) => [copy, ...(prev ?? [])]);
        showSuccess('Resume duplicated');
      } catch (e) {
        showError('Could not duplicate resume', e instanceof Error ? e.message : 'Please try again.');
      }
    },
    [showError, showSuccess, uid],
  );

  const remove = useCallback(
    async (id: string) => {
      const previous = resumes ?? [];
      setResumes(previous.filter((r) => r.id !== id));
      try {
        await deleteResume(uid, id);
        showSuccess('Resume deleted');
      } catch (e) {
        setResumes(previous);
        showError('Could not delete resume', e instanceof Error ? e.message : 'Please try again.');
      }
    },
    [resumes, showError, showSuccess, uid],
  );

  if (opening) {
    return (
      <div className="flex h-full items-center justify-center text-sm text-slate-500">
        <Loader2 className="mr-2 animate-spin" size={16} /> Opening your resume…
      </div>
    );
  }

  if (editing) {
    return (
      <ResumeEditorView
        uid={uid}
        initial={editing}
        fresh={fresh && editing.id === openId}
        onBack={() => {
          setEditing(null);
          void reload();
        }}
      />
    );
  }

  return (
    <div className="h-full overflow-y-auto px-4 pb-10 pt-4 sm:px-6">
      <section>
        <h2 className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">Your resumes</h2>
        <div className="mt-3">
          {resumes === null ? (
            <div className="flex items-center gap-2 text-sm text-slate-500">
              <Loader2 className="animate-spin" size={16} /> Loading…
            </div>
          ) : resumes.length === 0 ? (
            <p className="rounded-xl border border-dashed border-slate-300 px-4 py-5 text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">
              No resumes yet. Pick a template below to start one.
            </p>
          ) : (
            <ul className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              <AnimatePresence initial={false}>
                {resumes.map((r) => (
                  <motion.li key={r.id} layout {...fade}>
                    <ResumeCard resume={r} onOpen={setEditing} onDuplicate={duplicate} onDelete={remove} />
                  </motion.li>
                ))}
              </AnimatePresence>
            </ul>
          )}
        </div>
      </section>

      <section className="mt-8">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Start from a template
          </h2>
          <div className="flex flex-wrap gap-1.5">
            {TAGS.map((t) => (
              <button
                key={t.id}
                onClick={() => setTag(t.id)}
                className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
                  tag === t.id
                    ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        <motion.div layout className="mt-4 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4">
          <AnimatePresence initial={false}>
            {templates.map((preset) => (
              <motion.div key={preset.id} layout {...fade} className="relative">
                <TemplateCard preset={preset} onSelect={start} />
                {creating === preset.id && (
                  <div className="absolute inset-0 flex items-center justify-center rounded-2xl bg-white/70 backdrop-blur-sm dark:bg-slate-950/70">
                    <Loader2 className="animate-spin text-indigo-600" size={22} />
                  </div>
                )}
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>
      </section>
    </div>
  );
}
