steps:
  # Step 1: Build the Docker image with environment variables from substitution variables
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Building Docker image with environment variables from substitution variables..."
        
        # Build the Docker image with build arguments from substitution variables
        if [ -z '${COMMIT_SHA}' ]; then
          echo "Building image with tag: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"
            docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY='${_NEXT_PUBLIC_FIREBASE_API_KEY}' \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}' \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID='${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}' \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID='${_NEXT_PUBLIC_FIREBASE_APP_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}' \
            --build-arg NEXT_PUBLIC_JSEARCH_API_KEY='${_NEXT_PUBLIC_JSEARCH_API_KEY}' \
            --build-arg NEXT_PUBLIC_JSEARCH_API_HOST='${_NEXT_PUBLIC_JSEARCH_API_HOST}' \
            --build-arg NEXT_PUBLIC_TAVUS_API_KEY='${_NEXT_PUBLIC_TAVUS_API_KEY}' \
            --build-arg NEXT_PUBLIC_OPENAI_API_KEY='${_NEXT_PUBLIC_OPENAI_API_KEY}' \
            --build-arg NEXT_PUBLIC_RESUME_API_BASE_URL='${_NEXT_PUBLIC_RESUME_API_BASE_URL}' \
            --build-arg NEXT_PUBLIC_RESUME_API_MODEL_TYPE='${_NEXT_PUBLIC_RESUME_API_MODEL_TYPE}' \
            --build-arg NEXT_PUBLIC_RESUME_API_MODEL='${_NEXT_PUBLIC_RESUME_API_MODEL}' \
            -t '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest' \
            -f Dockerfile \
            .
        else
          echo "Building image with tag: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
            docker build \
            --build-arg NEXT_PUBLIC_FIREBASE_API_KEY='${_NEXT_PUBLIC_FIREBASE_API_KEY}' \
            --build-arg NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}' \
            --build-arg NEXT_PUBLIC_FIREBASE_PROJECT_ID='${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}' \
            --build-arg NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_APP_ID='${_NEXT_PUBLIC_FIREBASE_APP_ID}' \
            --build-arg NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}' \
            --build-arg NEXT_PUBLIC_JSEARCH_API_KEY='${_NEXT_PUBLIC_JSEARCH_API_KEY}' \
            --build-arg NEXT_PUBLIC_JSEARCH_API_HOST='${_NEXT_PUBLIC_JSEARCH_API_HOST}' \
            --build-arg NEXT_PUBLIC_TAVUS_API_KEY='${_NEXT_PUBLIC_TAVUS_API_KEY}' \
            --build-arg NEXT_PUBLIC_OPENAI_API_KEY='${_NEXT_PUBLIC_OPENAI_API_KEY}' \
            --build-arg NEXT_PUBLIC_RESUME_API_BASE_URL='${_NEXT_PUBLIC_RESUME_API_BASE_URL}' \
            --build-arg NEXT_PUBLIC_RESUME_API_MODEL_TYPE='${_NEXT_PUBLIC_RESUME_API_MODEL_TYPE}' \
            --build-arg NEXT_PUBLIC_RESUME_API_MODEL='${_NEXT_PUBLIC_RESUME_API_MODEL}' \
            -t '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}' \
            -f Dockerfile \
            .
        fi
    id: 'build-image'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Push the Docker image to Artifact Registry
        if [ -z '${COMMIT_SHA}' ]; then
          echo "Pushing image: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"
          docker push '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
        else
          echo "Pushing image: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
          docker push '${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}'
        fi
    id: 'push-image'

  # Step 3: Deploy to Cloud Run with environment variables from .env file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check if .env file exists
        if [ ! -f ".env" ]; then
          echo "Error: .env file not found. Please create a .env file with your environment variables."
          exit 1
        fi
        
        # Deploy to Cloud Run with environment variables from substitution variables
        echo "Deploying to Cloud Run with environment variables from substitution variables..."
        if [ -z '${COMMIT_SHA}' ]; then
          echo "Deploying image: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"
          gcloud run deploy ${_SERVICE_NAME} \
            --image='${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest' \
            --region=${_GAR_LOCATION} \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --memory=2Gi \
            --cpu=2 \
            --min-instances=0 \
            --max-instances=10 \
            --timeout=300 \
            --service-account=${_SERVICE_ACCOUNT_EMAIL} \
            --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_FIREBASE_API_KEY='${_NEXT_PUBLIC_FIREBASE_API_KEY}',NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',NEXT_PUBLIC_FIREBASE_PROJECT_ID='${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}',NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',NEXT_PUBLIC_FIREBASE_APP_ID='${_NEXT_PUBLIC_FIREBASE_APP_ID}',NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}',NEXT_PUBLIC_JSEARCH_API_KEY='${_NEXT_PUBLIC_JSEARCH_API_KEY}',NEXT_PUBLIC_JSEARCH_API_HOST='${_NEXT_PUBLIC_JSEARCH_API_HOST}',NEXT_PUBLIC_TAVUS_API_KEY='${_NEXT_PUBLIC_TAVUS_API_KEY}',NEXT_PUBLIC_OPENAI_API_KEY='${_NEXT_PUBLIC_OPENAI_API_KEY}',NEXT_PUBLIC_RESUME_API_BASE_URL='${_NEXT_PUBLIC_RESUME_API_BASE_URL}',NEXT_PUBLIC_RESUME_API_MODEL_TYPE='${_NEXT_PUBLIC_RESUME_API_MODEL_TYPE}',NEXT_PUBLIC_RESUME_API_MODEL='${_NEXT_PUBLIC_RESUME_API_MODEL}'"
        else
          echo "Deploying image: ${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}"
          gcloud run deploy ${_SERVICE_NAME} \
            --image='${_GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}' \
            --region=${_GAR_LOCATION} \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --memory=2Gi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --timeout=300 \
            --service-account=${_SERVICE_ACCOUNT_EMAIL} \
            --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_FIREBASE_API_KEY='${_NEXT_PUBLIC_FIREBASE_API_KEY}',NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN='${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',NEXT_PUBLIC_FIREBASE_PROJECT_ID='${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}',NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET='${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID='${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',NEXT_PUBLIC_FIREBASE_APP_ID='${_NEXT_PUBLIC_FIREBASE_APP_ID}',NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID='${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}',NEXT_PUBLIC_JSEARCH_API_KEY='${_NEXT_PUBLIC_JSEARCH_API_KEY}',NEXT_PUBLIC_JSEARCH_API_HOST='${_NEXT_PUBLIC_JSEARCH_API_HOST}',NEXT_PUBLIC_TAVUS_API_KEY='${_NEXT_PUBLIC_TAVUS_API_KEY}',NEXT_PUBLIC_OPENAI_API_KEY='${_NEXT_PUBLIC_OPENAI_API_KEY}',NEXT_PUBLIC_RESUME_API_BASE_URL='${_NEXT_PUBLIC_RESUME_API_BASE_URL}',NEXT_PUBLIC_RESUME_API_MODEL_TYPE='${_NEXT_PUBLIC_RESUME_API_MODEL_TYPE}',NEXT_PUBLIC_RESUME_API_MODEL='${_NEXT_PUBLIC_RESUME_API_MODEL}'"
        fi
    id: 'deploy-to-cloudrun'

# Substitution variables (can be overridden in trigger or command line)
# Set these values in Cloud Build trigger or via command line:
# gcloud builds submit --config=cloudbuild.yaml \
#   --substitutions=_GAR_LOCATION=us-central1,_REPOSITORY=myjobsearchagent-repo,_SERVICE_NAME=myjobsearchagent,_SERVICE_ACCOUNT_EMAIL=your-sa@project.iam.gserviceaccount.com .
substitutions:
  _GAR_LOCATION: ''
  _REPOSITORY: ''
  _SERVICE_NAME: ''
  _SERVICE_ACCOUNT_EMAIL: ''
  # Environment variables (passed from GitHub Secrets)
  _NEXT_PUBLIC_FIREBASE_API_KEY: ''
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ''
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ''
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ''
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ''
  _NEXT_PUBLIC_FIREBASE_APP_ID: ''
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ''
  _NEXT_PUBLIC_JSEARCH_API_KEY: ''
  _NEXT_PUBLIC_JSEARCH_API_HOST: ''
  _NEXT_PUBLIC_TAVUS_API_KEY: ''
  _NEXT_PUBLIC_OPENAI_API_KEY: ''
  _NEXT_PUBLIC_RESUME_API_BASE_URL: ''
  _NEXT_PUBLIC_RESUME_API_MODEL_TYPE: ''
  _NEXT_PUBLIC_RESUME_API_MODEL: ''
# Configure build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

# Build timeout
timeout: '1200s'