/**
 * The resume editor: content and design on the left, the live page on the
 * right. The preview is the same renderer the PDF is serialized from, so what
 * is on screen is what compiles.
 *
 * A résumé the AI just wrote for a job opens here directly (`fresh`), on the
 * Design tab so the first decision is the template, with the résumé and its
 * cover letter one click apart in the preview. Nothing else has to be opened:
 * match analysis, both documents, editing and export all live on this screen.
 */
import { motion } from 'framer-motion';
import { ArrowLeft, Check, Download, FileText, FileWarning, Loader2, Mail, Redo2, Sparkles, Undo2, X } from 'lucide-react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { serializeResume } from '../../../lib/resume/latex/serialize';
import { getPreset } from '../../../lib/resume/presets';
import type { ResumeDocument } from '../../../lib/resume/schema';
import { compileLatex } from '../../../services/documentService';
import { useToastContext } from '../../ui/ToastProvider';
import OpenInOverleafButton from '../../dashboard/documents/OpenInOverleafButton';
import ResumePreview, { type PreviewLayout } from '../ResumePreview';
import ContentPanel from './ContentPanel';
import CoverLetterPane from './CoverLetterPane';
import DesignPanel from './DesignPanel';
import InsightsPanel from './InsightsPanel';
import { useResumeEditor } from './useResumeEditor';

const FIT_PADDING = 48;
const PAGE_WIDTH_PT = { A4: 595.28, Letter: 612 };

type Tab = 'content' | 'design' | 'insights';
type Stage = 'resume' | 'cover';

interface Props {
  /** null runs the editor without persistence, for the dev harness. */
  uid: string | null;
  initial: ResumeDocument;
  /** Just generated by the AI: open on the template choice and say so. */
  fresh?: boolean;
  onBack: () => void;
}

export default function ResumeEditorView({ uid, initial, fresh = false, onBack }: Props) {
  const editor = useResumeEditor(uid, initial);
  const { document: doc, update, undo, redo, canUndo, canRedo, saveState, saveNow } = editor;
  const { showError } = useToastContext();

  const [tab, setTab] = useState<Tab>(fresh && initial.ai ? 'design' : 'content');
  const [stage, setStage] = useState<Stage>('resume');
  const [banner, setBanner] = useState(fresh && !!initial.ai);
  const tabs: Tab[] = doc.ai ? ['content', 'design', 'insights'] : ['content', 'design'];
  const tabLabel: Record<Tab, string> = { content: 'Content', design: 'Design', insights: 'Match' };

  const [layout, setLayout] = useState<PreviewLayout | null>(null);
  const [scale, setScale] = useState(0.7);
  const [downloading, setDownloading] = useState(false);
  const stageRef = React.useRef<HTMLDivElement>(null);

  // Fit the page to whatever width the preview column actually has.
  useEffect(() => {
    const el = stageRef.current;
    if (!el) return;
    const pageWidth = PAGE_WIDTH_PT[doc.layout.pageFormat];
    const fit = () => setScale(Math.min(1, Math.max(0.35, (el.clientWidth - FIT_PADDING) / (pageWidth / 0.75))));
    fit();
    const observer = new ResizeObserver(fit);
    observer.observe(el);
    return () => observer.disconnect();
  }, [doc.layout.pageFormat]);

  const tex = useMemo(() => serializeResume(doc), [doc]);

  const download = useCallback(async () => {
    setDownloading(true);
    try {
      await saveNow();
      const blob = await compileLatex(tex);
      const url = URL.createObjectURL(blob);
      const a = window.document.createElement('a');
      a.href = url;
      a.download = `${doc.title.replace(/[^\w-]+/g, '_') || 'resume'}.pdf`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      showError('Could not build the PDF', e instanceof Error ? e.message : 'Please try again.');
    } finally {
      setDownloading(false);
    }
  }, [doc.title, saveNow, showError, tex]);

  const seg = (active: boolean) =>
    `flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors ${
      active ? 'bg-white text-slate-900 shadow-sm dark:bg-slate-700 dark:text-white' : 'text-slate-500 hover:text-slate-700 dark:text-slate-400'
    }`;

  return (
    <div className="flex h-full min-h-0 flex-col">
      <header className="flex flex-wrap items-center gap-2 border-b border-slate-200/70 bg-white/80 px-3 py-2 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-900/80">
        <button
          onClick={onBack}
          className="flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-sm text-slate-600 transition-colors hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"
        >
          <ArrowLeft size={16} />
          Resumes
        </button>

        <input
          value={doc.title}
          onChange={(e) => update((d) => { d.title = e.target.value; })}
          className="min-w-0 flex-1 rounded-lg bg-transparent px-2 py-1 text-sm font-semibold text-slate-900 outline-none focus:bg-slate-100 dark:text-white dark:focus:bg-slate-800"
          aria-label="Resume title"
        />

        <div className="flex items-center gap-1">
          <button onClick={undo} disabled={!canUndo} aria-label="Undo" className="rounded-lg p-2 text-slate-500 transition-colors hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-800">
            <Undo2 size={16} />
          </button>
          <button onClick={redo} disabled={!canRedo} aria-label="Redo" className="rounded-lg p-2 text-slate-500 transition-colors hover:bg-slate-100 disabled:opacity-30 dark:hover:bg-slate-800">
            <Redo2 size={16} />
          </button>
          <SaveBadge state={saveState} />
          <OpenInOverleafButton tex={tex} filename={`${doc.id}.tex`} />
          <button
            onClick={download}
            disabled={downloading}
            className="flex items-center gap-1.5 rounded-lg bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white transition-transform hover:scale-[1.02] active:scale-95 disabled:opacity-60"
          >
            {downloading ? <Loader2 size={15} className="animate-spin" /> : <Download size={15} />}
            PDF
          </button>
        </div>
      </header>

      <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
        <aside className="flex w-full min-w-0 flex-col border-slate-200 lg:w-[420px] lg:border-r dark:border-slate-800">
          {banner && doc.ai && (
            <motion.div
              initial={{ opacity: 0, y: -6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
              className="m-2 mb-0 flex items-start gap-2.5 rounded-xl border border-indigo-200 bg-indigo-50 p-3 dark:border-indigo-900 dark:bg-indigo-950/50"
            >
              <Sparkles size={16} className="mt-0.5 shrink-0 text-indigo-600 dark:text-indigo-400" />
              <div className="min-w-0 flex-1 text-xs leading-snug text-indigo-950 dark:text-indigo-100">
                <p className="font-semibold">
                  Ready for {doc.ai.jobTitle} at {doc.ai.company} · {doc.ai.analysis.match_score}% match
                </p>
                <p className="mt-0.5 text-indigo-800/80 dark:text-indigo-200/80">
                  Pick a template — your résumé re-flows instantly. Your cover letter is one click away above the preview.
                </p>
              </div>
              <button
                onClick={() => setBanner(false)}
                aria-label="Dismiss"
                className="rounded p-1 text-indigo-400 transition-colors hover:text-indigo-700"
              >
                <X size={14} />
              </button>
            </motion.div>
          )}

          <div className="flex gap-1 p-2">
            {tabs.map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`relative flex-1 rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${
                  tab === t ? 'text-slate-900 dark:text-white' : 'text-slate-500 hover:text-slate-700 dark:text-slate-400'
                }`}
              >
                {tab === t && (
                  <motion.span
                    layoutId="editor-tab"
                    transition={{ type: 'spring', stiffness: 500, damping: 40 }}
                    className="absolute inset-0 rounded-lg bg-slate-100 dark:bg-slate-800"
                  />
                )}
                <span className="relative">{tabLabel[t]}</span>
              </button>
            ))}
          </div>
          <div className="min-h-0 flex-1 overflow-y-auto px-3 pb-8">
            {/* The incoming panel animates in on its own. An exit animation
                would put this behind AnimatePresence's mode="wait", which
                stalls the whole subtree if a frame never lands. */}
            <motion.div
              key={tab}
              initial={{ opacity: 0, x: 8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.18, ease: [0.22, 1, 0.36, 1] }}
            >
              {tab === 'content' && <ContentPanel editor={editor} />}
              {tab === 'design' && <DesignPanel editor={editor} />}
              {tab === 'insights' && doc.ai && <InsightsPanel ai={doc.ai} />}
            </motion.div>
          </div>
        </aside>

        <section ref={stageRef} className="min-h-0 flex-1 overflow-y-auto bg-slate-100 p-6 pt-3 dark:bg-slate-950">
          <div className="mb-3 flex items-center justify-between gap-3">
            {doc.ai ? (
              <div className="flex gap-1 rounded-lg bg-slate-200/70 p-0.5 dark:bg-slate-800" role="tablist" aria-label="Document">
                <button role="tab" aria-selected={stage === 'resume'} className={seg(stage === 'resume')} onClick={() => setStage('resume')}>
                  <FileText size={13} /> Resume
                </button>
                <button role="tab" aria-selected={stage === 'cover'} className={seg(stage === 'cover')} onClick={() => setStage('cover')}>
                  <Mail size={13} /> Cover letter
                </button>
              </div>
            ) : (
              <span />
            )}
            <span className="text-xs text-slate-500">
              {stage === 'resume'
                ? `${getPreset(doc.presetId).name} · ${layout ? `${layout.pageCount} page${layout.pageCount === 1 ? '' : 's'}` : 'measuring…'}`
                : 'Cover letter'}
            </span>
          </div>

          {stage === 'cover' && doc.ai ? (
            <CoverLetterPane ai={doc.ai} />
          ) : (
            <ResumePreview document={doc} scale={scale} onLayout={setLayout} />
          )}
        </section>
      </div>
    </div>
  );
}

function SaveBadge({ state }: { state: 'idle' | 'saving' | 'saved' | 'error' }) {
  if (state === 'idle') return null;
  const map = {
    saving: { icon: <Loader2 size={13} className="animate-spin" />, text: 'Saving', cls: 'text-slate-400' },
    saved: { icon: <Check size={13} />, text: 'Saved', cls: 'text-emerald-600' },
    error: { icon: <FileWarning size={13} />, text: 'Not saved', cls: 'text-amber-600' },
  } as const;
  const { icon, text, cls } = map[state];
  return (
    <span className={`flex items-center gap-1 px-2 text-xs ${cls}`} role="status">
      {icon}
      {text}
    </span>
  );
}
