/**
 * Turn a generated LaTeX body back into a ResumeDocument.
 *
 * This is not a LaTeX parser and does not try to be. The AI writes against a
 * closed macro contract that we defined (macros.md), and sanitize.ts rejects
 * anything outside it before a document is ever compiled — so the input here is
 * always a short, known grammar:
 *
 *   \resheader{name}{contact}   \section{Title}      \resline{paragraph}
 *   \resskills{cat}{values}     \resrole{t}{c}{l}{d} \resedu{d}{i}{l}{d}
 *   \resproject{n}{tech}{d}     \rescert{c}{i}{d}    reslist / \resitem{…}
 *
 * with \textbf, \textit, \href and \resdot allowed inside arguments.
 *
 * Recovering the structure is what lets an AI-written resume be opened in the
 * editor and re-rendered in any template: once it is a ResumeDocument, the
 * LaTeX is generated by our own serializer, so it always compiles and always
 * matches the preview.
 */
import { createEntry, createResume, createSection } from '../defaults';
import { DEFAULT_PRESET_ID } from '../presets';
import { coerceResume, toPartialDate } from './coerce';
import type { Entry, Personal, ResumeDocument, RichBlock, RichText, RichTextNode, Section, SectionType } from '../schema';

/** An argument list read from a macro call, with the index just past it. */
interface Args {
  values: string[];
  end: number;
}

/** Read `count` brace-delimited arguments starting at `from`, respecting nesting. */
function readArgs(src: string, from: number, count: number): Args | null {
  const values: string[] = [];
  let i = from;
  for (let n = 0; n < count; n += 1) {
    while (i < src.length && /\s/.test(src[i])) i += 1;
    if (src[i] !== '{') return null;
    let depth = 0;
    const start = i + 1;
    for (; i < src.length; i += 1) {
      if (src[i] === '\\') {
        i += 1;
        continue;
      }
      if (src[i] === '{') depth += 1;
      else if (src[i] === '}') {
        depth -= 1;
        if (depth === 0) break;
      }
    }
    if (depth !== 0) return null;
    values.push(src.slice(start, i));
    i += 1;
  }
  return { values, end: i };
}

/** Undo the escaping applied on the way out, so the editor shows real text. */
function unescape(tex: string): string {
  return tex
    .replace(/\\textbackslash\{\}/g, '\u0001')
    .replace(/\\textasciitilde\{\}/g, '~')
    .replace(/\\textasciicircum\{\}/g, '^')
    .replace(/\\textless\{\}/g, '<')
    .replace(/\\textgreater\{\}/g, '>')
    .replace(/\\([%&$#_{}])/g, '$1')
    // The serializer breaks TeX ligatures with empty groups; drop them again.
    .replace(/([-'`!?])\{\}/g, '$1')
    .replace(/~/g, ' ')
    .replace(/\u0001/g, '\\')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Inline runs: \textbf, \textit and \href become marks, everything else text. */
export function parseInline(tex: string): RichTextNode[] {
  const out: RichTextNode[] = [];
  const push = (text: string, marks?: RichTextNode['marks']) => {
    const clean = unescape(text);
    if (!clean) return;
    const last = out[out.length - 1];
    const same = JSON.stringify(last?.marks ?? null) === JSON.stringify(marks ?? null);
    if (last && same) last.text += (last.text.endsWith(' ') || clean.startsWith(' ') ? '' : ' ') + clean;
    else out.push(marks ? { type: 'text', text: clean, marks } : { type: 'text', text: clean });
  };

  let plain = '';
  let i = 0;
  while (i < tex.length) {
    const rest = tex.slice(i);
    const command = rest.match(/^\\(textbf|textit|emph|href|resdot)/);
    if (!command) {
      plain += tex[i];
      i += 1;
      continue;
    }
    push(plain);
    plain = '';
    const name = command[1];
    if (name === 'resdot') {
      plain += ' · ';
      i += command[0].length;
      continue;
    }
    const args = readArgs(tex, i + command[0].length, name === 'href' ? 2 : 1);
    if (!args) {
      plain += tex[i];
      i += 1;
      continue;
    }
    if (name === 'href') {
      push(args.values[1], [{ type: 'link', attrs: { href: unescape(args.values[0]) } }]);
    } else {
      // Nested emphasis is rare in generated output; the outer mark wins.
      push(args.values[0], [{ type: name === 'textbf' ? 'bold' : 'italic' }]);
    }
    i = args.end;
  }
  push(plain);
  return out;
}

const plainText = (tex: string): string => parseInline(tex).map((n) => n.text).join('').trim();

const paragraph = (tex: string): RichText => {
  const content = parseInline(tex);
  return { type: 'doc', content: content.length ? [{ type: 'paragraph', content }] : [] };
};

const bullets = (items: string[]): RichText => ({
  type: 'doc',
  content: items.length
    ? [
        {
          type: 'bulletList',
          content: items.map((item) => ({
            type: 'listItem' as const,
            content: [{ type: 'paragraph' as const, content: parseInline(item) }],
          })),
        },
      ]
    : [],
});

/** Split "2021 -- Present" into the entry's date fields. */
export function parseDateRange(value: string): Pick<Entry, 'startDate' | 'endDate' | 'current'> {
  const text = plainText(value);
  if (!text) return { startDate: '', endDate: '', current: false };
  const parts = text.split(/\s*(?:--|–|—|-|to)\s*/i).filter(Boolean);
  const isNow = (s: string) => /^(present|current|now|ongoing)$/i.test(s.trim());
  if (parts.length === 1) {
    return isNow(parts[0])
      ? { startDate: '', endDate: '', current: true }
      : { startDate: toPartialDate(parts[0]), endDate: '', current: false };
  }
  const [start, end] = parts;
  return isNow(end)
    ? { startDate: toPartialDate(start), endDate: '', current: true }
    : { startDate: toPartialDate(start), endDate: toPartialDate(end), current: false };
}

/** Which section type a heading and its macros describe. */
const TITLE_HINTS: [RegExp, SectionType][] = [
  [/summary|profile|objective|about/i, 'summary'],
  [/experience|employment|work history|career/i, 'experience'],
  [/education|academic/i, 'education'],
  [/project/i, 'projects'],
  [/skill|technolog|competenc/i, 'skills'],
  [/certificat|licen[cs]e/i, 'certifications'],
  [/award|honou?r|achievement/i, 'awards'],
  [/language/i, 'languages'],
  [/interest|hobb|volunteer/i, 'interests'],
];

/** The macro used inside a section is stronger evidence than its title. */
const MACRO_TYPE: Record<string, SectionType> = {
  resrole: 'experience',
  resedu: 'education',
  resproject: 'projects',
  resskills: 'skills',
  rescert: 'certifications',
};

function sectionTypeFor(title: string, macros: string[]): SectionType {
  for (const macro of macros) {
    const type = MACRO_TYPE[macro];
    if (type) return type;
  }
  for (const [pattern, type] of TITLE_HINTS) if (pattern.test(title)) return type;
  return macros.includes('resline') ? 'summary' : 'custom';
}

const PHONE = /^[+(]?[\d][\d\s().+-]{6,}$/;

/** Split the header's contact line into the fields the editor edits. */
export function parseContactLine(tex: string): Omit<Personal, 'fullName' | 'jobTitle'> {
  const personal = { email: '', phone: '', location: '', links: [] as Personal['links'] };
  const parts = tex.split(/\\resdot/).map((p) => p.trim()).filter(Boolean);
  parts.forEach((part, index) => {
    const nodes = parseInline(part);
    const link = nodes.find((n) => n.marks?.some((m) => m.type === 'link'));
    if (link) {
      const href = link.marks!.find((m) => m.type === 'link') as { attrs: { href: string } };
      personal.links.push({ id: `l${index}`, label: link.text.trim(), url: href.attrs.href });
      return;
    }
    const text = nodes.map((n) => n.text).join('').trim();
    if (!text) return;
    if (text.includes('@') && !personal.email) personal.email = text;
    else if (PHONE.test(text) && !personal.phone) personal.phone = text;
    else if (/^https?:\/\/|\.(com|io|dev|net|org)\b/i.test(text)) {
      personal.links.push({ id: `l${index}`, label: text, url: /^https?:/i.test(text) ? text : `https://${text}` });
    } else if (!personal.location) personal.location = text;
  });
  return personal;
}

interface RawSection {
  title: string;
  macros: string[];
  entries: Entry[];
  /** Bullets seen before any entry; they belong to the section itself. */
  loose: string[];
}

/**
 * Parse a generated body. Unknown commands are skipped rather than failing:
 * a partial import the user can fix beats an error they cannot.
 */
/**
 * The part of a generated file that holds the résumé itself.
 *
 * A full document begins with a preamble whose comments and \newcommand lines
 * *mention* every macro (`% \\resrole{Job Title}{Company}…`). Read as content,
 * those produce phantom sections and entries — an imported résumé came back with
 * an extra "Experience" full of preamble examples. So: keep only what sits
 * between \begin{document} and \end{document} when those exist, and drop
 * comments (an unescaped % to end of line) either way.
 */
export function extractBody(source: string): string {
  const BEGIN = '\\begin{document}';
  const END = '\\end{document}';
  const begin = source.indexOf(BEGIN);
  const end = source.lastIndexOf(END);
  const inner = begin === -1 ? source : source.slice(begin + BEGIN.length, end > begin ? end : undefined);
  // An unescaped % starts a comment that runs to the end of the line.
  return inner.replace(/(^|[^\\])%.*$/gm, '$1');
}

export function resumeFromMacroBody(
  source: string,
  options: { title?: string; presetId?: string; jobTitle?: string } = {},
): ResumeDocument {
  const body = extractBody(source);
  const doc = createResume({ presetId: options.presetId ?? DEFAULT_PRESET_ID, title: options.title ?? 'Imported resume', sections: [] });
  const raw: RawSection[] = [];
  let current: RawSection | null = null;
  // An object, not a `let`: TypeScript cannot narrow a variable that closures assign.
  const cursor: { entry: Entry | null } = { entry: null };

  const openSection = (title: string) => {
    current = { title, macros: [], entries: [], loose: [] };
    raw.push(current);
    cursor.entry = null;
  };
  const ensureSection = () => {
    if (!current) openSection('');
    return current!;
  };
  const addEntry = (macro: string, entry: Entry) => {
    const section = ensureSection();
    section.macros.push(macro);
    section.entries.push(entry);
    cursor.entry = entry;
  };

  let i = 0;
  while (i < body.length) {
    const match = body.slice(i).match(/^\\([a-zA-Z]+)/);
    if (!match) {
      i += 1;
      continue;
    }
    const name = match[1];
    const after = i + match[0].length;

    if (name === 'resheader') {
      const args = readArgs(body, after, 2);
      if (args) {
        doc.personal = {
          ...doc.personal,
          fullName: plainText(args.values[0]),
          jobTitle: options.jobTitle ?? '',
          ...parseContactLine(args.values[1]),
        };
        i = args.end;
        continue;
      }
    } else if (name === 'section') {
      const args = readArgs(body, after, 1);
      if (args) {
        openSection(plainText(args.values[0]));
        i = args.end;
        continue;
      }
    } else if (name === 'resline') {
      const args = readArgs(body, after, 1);
      if (args) {
        addEntry('resline', createEntry({ description: paragraph(args.values[0]) }));
        i = args.end;
        continue;
      }
    } else if (name === 'resskills') {
      const args = readArgs(body, after, 2);
      if (args) {
        addEntry('resskills', createEntry({ title: plainText(args.values[0]), subtitle: plainText(args.values[1]) }));
        i = args.end;
        continue;
      }
    } else if (name === 'resrole' || name === 'resedu') {
      const args = readArgs(body, after, 4);
      if (args) {
        const [title, org, location, dates] = args.values;
        addEntry(
          name,
          createEntry({
            title: plainText(title),
            subtitle: plainText(org),
            location: plainText(location),
            ...parseDateRange(dates),
          }),
        );
        i = args.end;
        continue;
      }
    } else if (name === 'resproject' || name === 'rescert') {
      const args = readArgs(body, after, 3);
      if (args) {
        const [title, second, dates] = args.values;
        addEntry(
          name,
          createEntry({ title: plainText(title), subtitle: plainText(second), ...parseDateRange(dates) }),
        );
        i = args.end;
        continue;
      }
    } else if (name === 'resitem') {
      const args = readArgs(body, after, 1);
      if (args) {
        const section = ensureSection();
        const target = cursor.entry;
        if (target) {
          const list = target.description.content.find(
            (b: RichBlock): b is Extract<RichBlock, { type: 'bulletList' }> => b.type === 'bulletList',
          );
          const item = { type: 'listItem' as const, content: [{ type: 'paragraph' as const, content: parseInline(args.values[0]) }] };
          if (list) list.content.push(item);
          else target.description.content.push({ type: 'bulletList', content: [item] });
        } else {
          section.loose.push(args.values[0]);
        }
        i = args.end;
        continue;
      }
    }

    i = after;
  }

  doc.sections = raw
    .map((section): Section | null => {
      const entries = section.entries.slice();
      if (section.loose.length) entries.unshift(createEntry({ description: bullets(section.loose) }));
      if (!entries.length) return null;
      const type = sectionTypeFor(section.title, section.macros);
      return createSection(type, section.title ? { title: section.title, entries } : { entries });
    })
    .filter((s): s is Section => s !== null);

  // AI output is not bound by our limits; repair rather than let the schema reject it.
  return coerceResume<ResumeDocument>(doc);
}
