/**
 * Assembles a complete, self-contained .tex file from the fixed preamble plus
 * an AI-generated body.
 *
 * Self-contained matters for two reasons: Texapi's simple JSON endpoint takes
 * a single string, and Overleaf's `encoded_snip` import works best with one
 * file (no .sty upload, no multi-file project to manage).
 */
import fs from 'fs';
import path from 'path';
import { sanitizeBody, type DocumentKind } from './sanitize';

const TEMPLATE_DIR = path.join(process.cwd(), 'src', 'server', 'latex', 'templates');

/**
 * Templates are read from disk rather than inlined as TS strings so they stay
 * real .tex files — editable, and directly compilable for debugging.
 * `outputFileTracingIncludes` in next.config.mjs ships them with the build.
 */
const cache = new Map<string, string>();

function readTemplate(name: string): string {
  const cached = cache.get(name);
  if (cached !== undefined) return cached;

  const contents = fs.readFileSync(path.join(TEMPLATE_DIR, name), 'utf8');
  // Windows checkouts produce CRLF; TeX is happier with LF.
  const normalised = contents.replace(/\r\n/g, '\n');
  cache.set(name, normalised);
  return normalised;
}

const WELCOME_COMMENT = `% Generated by AIJobSearchAgent.
% Edit freely — this is a complete, standalone LaTeX document.
% Compile with pdflatex.
`;

/**
 * @param body  AI-generated body. Sanitized here; callers do not pre-clean it.
 * @returns complete .tex source ready to compile or hand to Overleaf.
 */
export function buildDocument(body: string, kind: DocumentKind): string {
  const clean = sanitizeBody(body, kind);
  const macros = readTemplate(
    kind === 'resume' ? 'resume.macros.tex' : 'coverletter.macros.tex',
  );

  return [
    WELCOME_COMMENT,
    readTemplate('common.tex'),
    macros,
    '\\begin{document}',
    '',
    clean.replace(/\r\n/g, '\n').trim(),
    '',
    '\\end{document}',
    '',
  ].join('\n');
}

/** Exposed so prompts can embed the macro list without duplicating it. */
export function readMacroReference(kind: DocumentKind): string {
  return readTemplate(kind === 'resume' ? 'resume.macros.tex' : 'coverletter.macros.tex');
}
